version: '3'
services:
  frontend:
    image: tonanuvem/frontend_clientes_microservice:latest
    deploy:
        replicas: 3
        restart_policy:
            condition: on-failure
            max_attempts: 3
    ports:
      - "8000:80"
    networks:
      - net
      
  backend:
    image: tonanuvem/backend_clientes_microservice:latest
    deploy:
        replicas: 3
        restart_policy:
            condition: on-failure
            max_attempts: 3
    ports:
      - "5000:5000"
    networks:
      - net
      
  mongo:
    image: mongo:latest
    volumes:
      - data:/data
    deploy:
      restart_policy:
            condition: on-failure
            max_attempts: 3
    ports:
      - "27017:27017"
    networks:
      - net

  mongoexpress:
    image: mongo-express
    ports:
      - "8081:8081"
    networks:
      - net
        
  visualizador:
    image: dockersamples/visualizer
    volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
    - 8080:8080
    deploy:
      placement:
        constraints:
          - node.role == manager

volumes:
  data:
  
networks:
  net:
    external: true
